# Generated by Django 4.0.5 on 2022-06-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_alter_item_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('list', 'text')},
        ),
    ]
